### ISSUE TITLE
Screen with duplicate options when starting Zingo PC.

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-pc#48]
**Describe the bug**
When you start Zingo PC and tap on **Create a new account**, another screen opens where the same option is displayed again.

**To Reproduce**
1. Launch the app
2. Tap on Create new wallet

![IMG_20230509_191204_465.png](https://github.com/zingolabs/zingo-pc/assets/37910384/ca2ed53a-287f-4f73-8e37-8863d23df161)

![IMG_20230509_191212_951.png](https://github.com/zingolabs/zingo-pc/assets/37910384/e8be3ebb-edd7-43c3-b153-fce9ac79a044)

An error appears in the "Console" and instead of creating the new wallet, another screen opens where the Create new wallet and Restore button appears again.

Error: _Cannot create a new wallet from seed, because a wallet already exists_

**Expected behavior**
Tapping on **Create new wallet** should create the wallet, it should not open the old screen with the same options.

**Desktop:**
 - OS: Windows 10
 - Version: v0.0.1

**Additional context**
This old screen generates an error when tapping **Restore from the seed phrase**, but since the intent is to remove this screen, no reporting is necessary. The error does not appear when tapping on **Restore from the new main screen**.

**Comment by juanky201271** [comment]
I need to fix a specific use case: When you start the App & it cannot start the current wallet you can't do anything with the App. If you try to `create` a new wallet or you try to `restore` from seed, you got the same error, because you have the useless wallet file there. We have to implement a new feature in `zingolib` to remove this file when the user decide to click on `create` or `restore`.
@AloeareV @zancas
